spring:
  application:
    name: Demo-LLM

  ai:
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      api-key: ${DASHSCOPE_API_KEY}
      chat:
        options:
          model: qwq-plus
          temperature: 1.0
      embedding:
        options:
          model: text-embedding-v3
          dimensions: 1024

  # Redis Configuration
  data:
    redis:
      host: 10.122.195.240
      port: 6379
      database: 1
      password: 123456

  servlet:
    multipart:
      max-file-size: 104857600
      max-request-size: 104857600


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo-llm-db
    username: root
    password: 123456

logging:
  level:
    org.springframework.ai.chat.client.advisor: debug
    com.example: debug


